# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [4]:
s="Hi there Sam!"
s=s.split()
print(s);



['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [5]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));





The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)





['hello']


# Numpy

In [7]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
import numpy as np
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [11]:
import numpy as np
np.arange(20,35)



array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
import numpy as np
np.arange(0,9).reshape((3,3))




array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))





array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd
data=[['bharathi',66],['shalini',60],['veera',70]]
df=pd.DataFrame(data,columns=['Name','Age'])
(df)

Name  Age
0  bharathi   66
1   shalini   60
2     veera   70

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [25]:
import pandas as pd
per1=pd.date_range(start='1-1-2023',end='02-10-2023',freq='5H')
for val in per1:
  print(val)






2023-01-01 00:00:00
2023-01-01 05:00:00
2023-01-01 10:00:00
2023-01-01 15:00:00
2023-01-01 20:00:00
2023-01-02 01:00:00
2023-01-02 06:00:00
2023-01-02 11:00:00
2023-01-02 16:00:00
2023-01-02 21:00:00
2023-01-03 02:00:00
2023-01-03 07:00:00
2023-01-03 12:00:00
2023-01-03 17:00:00
2023-01-03 22:00:00
2023-01-04 03:00:00
2023-01-04 08:00:00
2023-01-04 13:00:00
2023-01-04 18:00:00
2023-01-04 23:00:00
2023-01-05 04:00:00
2023-01-05 09:00:00
2023-01-05 14:00:00
2023-01-05 19:00:00
2023-01-06 00:00:00
2023-01-06 05:00:00
2023-01-06 10:00:00
2023-01-06 15:00:00
2023-01-06 20:00:00
2023-01-07 01:00:00
2023-01-07 06:00:00
2023-01-07 11:00:00
2023-01-07 16:00:00
2023-01-07 21:00:00
2023-01-08 02:00:00
2023-01-08 07:00:00
2023-01-08 12:00:00
2023-01-08 17:00:00
2023-01-08 22:00:00
2023-01-09 03:00:00
2023-01-09 08:00:00
2023-01-09 13:00:00
2023-01-09 18:00:00
2023-01-09 23:00:00
2023-01-10 04:00:00
2023-01-10 09:00:00
2023-01-10 14:00:00
2023-01-10 19:00:00
2023-01-11 00:00:00
2023-01-11 05:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [48]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df= pd.DataFrame (lists, columns = ['FNames', 'LName', 'Age'])
print(df)



   FNames LName  Age
0       1   aaa   22
1       2   bbb   25
2       3   ccc   24
